import type { AuditLog } from "./audit.js";
import type { Corpus } from "./types.js";
import type { Community, MemberState } from "./radar.js";

export interface SponsorConfig {
  name: string;
  /** Exact anchor text the sponsor asked for, if any. */
  anchorText?: string;
  url?: string;
  deliverable?: string;
}

export interface ReportInput {
  community: Community;
  audit: AuditLog;
  corpus: Corpus;
  now: number;
  deadlineAt: number;
  /** "synthetic-replay" marks every number as demo data; "live" omits the mark. */
  mode: "live" | "synthetic-replay";
  sponsor?: SponsorConfig;
}

const STATES: MemberState[] = ["registered", "joined", "introduced", "active", "submitted"];

function countBy<T>(items: readonly T[], key: (item: T) => string): Map<string, number> {
  const m = new Map<string, number>();
  for (const item of items) m.set(key(item), (m.get(key(item)) ?? 0) + 1);
  return m;
}

function pct(part: number, whole: number): string {
  return whole === 0 ? "—" : `${Math.round((part / whole) * 100)}%`;
}

function iso(ms: number): string {
  return new Date(ms).toISOString().replace("T", " ").slice(0, 16) + "Z";
}

/**
 * One-click sponsor/engagement report. Everything is computed from the audit
 * trail and community state — the numbers are reproducible, not hand-written.
 */
export function generateReport(input: ReportInput): string {
  const { community, audit, corpus, now, deadlineAt, mode, sponsor } = input;
  const members = community.list();
  const events = audit.list();

  const stateCounts = countBy(members, (m) => m.state);
  const eventCounts = countBy(events, (e) => e.kind);

  const withLastMsg = members.filter((m) => m.lastMessageAt !== undefined);
  const active72 = withLastMsg.filter((m) => now - (m.lastMessageAt ?? 0) <= 72 * 3_600_000).length;
  const total = members.length;
  const submitted = stateCounts.get("submitted") ?? 0;

  const contradictions = events.filter((e) => e.kind === "contradiction.found");

  const lines: string[] = [];
  lines.push(`# Engagement Report — ${corpus.event}`);
  lines.push("");
  lines.push(`Generated: ${iso(now)} · Data as of corpus curation ${corpus.curatedAt}`);
  lines.push(`Submission deadline: ${iso(deadlineAt)} (${Math.round((deadlineAt - now) / 3_600_000)}h remaining)`);
  if (mode === "synthetic-replay") {
    lines.push("");
    lines.push(
      `> **Synthetic replay.** Every number below is computed from the built-in ${total}-member demo community and this machine's audit trail — not from a live event.`,
    );
  }
  lines.push("");

  lines.push("## Participation funnel");
  lines.push("");
  lines.push("| Stage | Participants | Conversion |");
  lines.push("|---|---|---|");
  for (const state of STATES) {
    const count = stateCounts.get(state) ?? 0;
    lines.push(`| ${state} | ${count} | ${pct(count, total)} |`);
  }
  lines.push("");

  lines.push("## Engagement");
  lines.push("");
  lines.push(`- Registered participants: ${total}`);
  lines.push(`- Ever posted a message: ${withLastMsg.length} (${pct(withLastMsg.length, total)})`);
  lines.push(`- Active in the last 72h: ${active72} (${pct(active72, total)})`);
  lines.push(`- Submitted: ${submitted} (${pct(submitted, total)})`);
  lines.push("");

  lines.push("## Support load (AI copilot)");
  lines.push("");
  lines.push(`- Questions answered with citations: ${eventCounts.get("faq.answered") ?? 0}`);
  lines.push(`- Escalated to humans (no reliable source): ${eventCounts.get("faq.escalated") ?? 0}`);
  lines.push(`- Refused on a verified doc conflict: ${eventCounts.get("faq.conflicted") ?? 0}`);
  lines.push(`- Documentation conflicts surfaced: ${contradictions.length}`);
  for (const c of contradictions) {
    lines.push(`  - ${c.summary}`);
  }
  lines.push("");

  lines.push("## Outreach (all human-approved)");
  lines.push("");
  lines.push(`- Drafted: ${eventCounts.get("outreach.drafted") ?? 0}`);
  lines.push(`- Approved by organizer: ${eventCounts.get("outreach.approved") ?? 0}`);
  lines.push(`- Sent (real sender): ${eventCounts.get("outreach.sent") ?? 0}`);
  lines.push(`- Simulated (demo sender — nothing delivered): ${eventCounts.get("outreach.simulated") ?? 0}`);
  lines.push(`- Send failed (awaiting retry): ${eventCounts.get("outreach.send_failed") ?? 0}`);
  lines.push(`- Rejected: ${eventCounts.get("outreach.rejected") ?? 0}`);
  lines.push("");

  if (sponsor) {
    lines.push(`## Sponsor deliverables — ${sponsor.name}`);
    lines.push("");
    if (sponsor.anchorText && sponsor.url) {
      lines.push(`- Mention placement: [${sponsor.anchorText}](${sponsor.url})`);
    }
    if (sponsor.deliverable) {
      lines.push(`- Status: ${sponsor.deliverable}`);
    }
    lines.push(`- Reach: this report covers ${total} registered participants and ${events.length} logged interactions.`);
    lines.push("");
  }

  lines.push("---");
  lines.push(
    "*Generated by Greenroom, deterministically, from `data/runtime/audit.jsonl` and the community event log — open those files to reproduce every number on this page.*",
  );
  return lines.join("\n");
}
